options:
  access-key:
    type: string
    default: "1jwKgLYi/CdfBTI9KByfYxwyQ6HUIEfnGSgakdpFjgk="
    description: "Fake device access key for DeviceHive"
  device-key:
    type: string
    default: "00000000-0000-0000-0000-000000000000"
    description: "Device Key for filtering in DeviceHive"
  device-class:
    type: string
    default: "go-gateway-class"
    description: "Filter for class of device"
  uuid: 
    type: string
    default: "f000aa1104514000b000000000000000"
    description: "UUID of equipment inside of this unit"
  interval: 
    type: int
    default: 1000
    description: "Interval in ms between 2 probes"
  value-change-interval: 
    type: int
    default: 10000
    description: "Interval in ms between 2 changes of interval"
  max-positive-value: 
    type: string
    default: "0.006"
    description: "Max probe value that can be emitted"
  max-negative-value: 
    type: string
    default: "1"
    description: "Min probe value that can be emitted"

