#!/bin/bash
# Validating I am running on debian-like OS
[ -f /etc/debian_version ] || {
	echo "We are not running on a Debian-like system. Exiting..."
	exit 0
}

set -ex 
# Load Configuration
MYNAME="$(readlink -f "$0")"
MYDIR="$(dirname "${MYNAME}")"
MYAPP="dh-stream-simulator"
MYCONF="${MYDIR}/../etc/${MYAPP}.conf"
MYLIB="${MYDIR}/../lib/bashlib.sh"
INSTALL_DIR="/opt"
# JUJULIB="${MYDIR}/../lib/jujulib.sh"


for file in "${MYCONF}" "${MYLIB}"; do
	[ -f ${file} ] && source ${file} || { 
		juju-log "Could not find required files. Exiting..."
	}
done 

if [ $(is_sudoer) -eq 0 ]; then
	die "You must be root or sudo to run this script"
fi

if [ -d "${INSTALL_DIR}/${MYAPP}" ]
then
	hooks/stop
	cp "${INSTALL_DIR}/${MYAPP}/config.json" ~/
	rm -rf "${INSTALL_DIR}/${MYAPP}"
fi

hooks/install

# mv ~/config.json "${INSTALL_DIR}/${MYAPP}/config.json" 

hooks/start

exit $?

